import Head from 'next/head'
import Image from 'next/image'
import styles from './styles.module.css'
import Header from '../../components/Header'
import SectionsCards from '../../components/Sections/Cards'

export default function Infantil() {
    return (
        <>
            <Head>
                <title>Moda Infantil</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <main className={styles.main}>
                <h1>Moda Infantil</h1>
                <SectionsCards />
            </main>
        </>
    )
}