import Head from 'next/head'
import Image from 'next/image'
import Footer from '../../components/Footer'
import Formulario from '../../components/Formulario'

export default function Cadastro() {

    return (
        <section>

            <div className='Modal'>
                <Head>

                    <title>Formulário</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main>
                    <h1>Formulário</h1>
                    <Formulario />
                </main>
            </div>
        </section>
    )
}

