import Head from 'next/head'
import Image from 'next/image'
import Footer from '../../components/Footer'
import Formulario from '../../components/Formulario'
import styles from './styles.module.css'

export default function Cadastro() {
    return (
        <section>
            <Head>
                <title>Formulário</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>Formulário</h1>
                <Formulario />
            </main>
        </section>
    )
}
