import Head from 'next/head'
import Image from 'next/image'
import styles from './styles.module.css'
import react, { useState, useEffect } from 'react'
import axios from 'axios'

export default function Mock() {

    const [resposta, setResposta] = useState([]);
    const [teste, setTeste] = useState([])

    useEffect(() => {
        axios.get('https://api-de-roupas-default-rtdb.firebaseio.com/roupas.json')
            .then(function (response) {
                setResposta(response.data);
            }
            )
    }, [])
    const click = () => {
        window.location.href = "/cadastro"
    }
    return (
        <>

            <Head>
                <title>Moda Feminina</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className={styles.cabecalho}>
                {/* <main className={styles.main}>
                    <h1>Moda Feminina</h1>
                </main> */}
                <section className={styles.cards}>
                    {resposta && Object.values(resposta).map((item) => {
                        return (
                            <div className={styles.card} onClick={click}>
                                <img src={item.img} />
                                <p>{item.name}</p>
                                <p>{item.price}</p>
                                <p>{item.size}</p>
                            </div>
                        )
                    }
                    )
                    }
                </section>

            </section>

        </>
    )

}


// const mock = [
//     {
//         roupasMasculina: [{
//             camisetas: [
//                 {
//                     img: '',
//                     name: '',
//                     price: '',
//                     size: '',
//                 },
//                 {
//                     img: '',
//                     name: '',
//                     price: '',
//                     size: '',
//                 },
//                 {
//                     img: '',
//                     name: '',
//                     price: '',
//                     size: '',
//                 },
//                 {
//                     img: '',
//                     name: '',
//                     price: '',
//                     size: '',
//                 },
//                 {
//                     img: '',
//                     name: '',
//                     price: '',
//                     size: '',
//                 },
//                 {
//                     img: '',
//                     name: '',
//                     price: '',
//                     size: '',
//                 },
//             ],
//             calcas: [
//                 {
//                     img: '',
//                     name: '',
//                     price: '',
//                     size: '',
//                 },
//             ],
//             burmudas: [
//                 {
//                     img: '',
//                     name: '',
//                     price: '',
//                     size: '',
//                 },
//             ]
//         }]
//     },
//     {
//         roupasFeminas: [{
//             camisetas: [{

//             }],
//             calcas: [{

//             }],
//             bermudas: [{

//             }]
//         }]
//     },
]
