import Head from 'next/head'
import Image from 'next/image'
import styles from './styles.module.css'
import react, { useState, useEffect } from 'react'
import axios from 'axios'

export default function CardsFeminina() {


    const [resposta, setResposta] = useState();
    const [selecionado, setSelecionado] = useState([]);
    const [size, setSize] = useState('selecione');

    useEffect(() => {
        axios.get('https://api-de-roupas-default-rtdb.firebaseio.com/roupas/femininas.json')

            .then(function (response) {
                setResposta(response?.data);
            })
    }, []);

    const [url, setUrl] = useState();
    useEffect(() => {
        if (typeof window !== "undefined") {
            const params = new URLSearchParams(window.location.search);
            let urlParams = undefined;
            params.forEach((value, key) => {
                urlParams = Object.assign({}, urlParams, {
                    [key]: value.toString(),
                });
            });
            setUrl(urlParams);
        }
    }, []);


    const filter = resposta && Object.values(resposta?.camisetas).filter((items) => {
        return items?.size === url?.size
    })

    const filtro = resposta && Object.values(resposta?.calcas).filter((items) => {
        return items?.size === url?.size
    })

    const filtrar = resposta && Object.values(resposta?.bermudas).filter((items) => {
        return items?.size === url?.size
    })



    return (
        <>
            <div className='lojas'>
                <Head>
                    <title>Moda Feminina</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <section className={styles.cabecalho}>
                    <h1>Moda Feminina</h1>
                    <div>
                        <div className={styles.filtro}>
                            <select onChange={(e) => setSize(e.target.value)}>
                                <option value='selecione'>Selecione</option>
                                <option value='Grande'>Grande</option>
                                <option value='Média'>Médio</option>
                                <option value='Pequena'>Pequeno</option>
                            </select>
                            <button onClick={() => window.location.href = `/setorFeminina?size=${size}`}>Filtrar</button>
                        </div>

                        <h2>Camisetas</h2>
                        {filter?.length > 0 ? (
                            <section className={styles.cardsFeminina}>
                                {filter.map((item) => {
                                    return (
                                        <div className={styles.card}>
                                            <img src={item.img} />
                                            <p>{item.name}</p>
                                            <p>{item.price}</p>
                                            <p>{item.size}</p>
                                            <button onClick={() => window.open("https://web.whatsapp.com/send?phone=5511945988406")}>Comprar</button>
                                        </div>
                                    )
                                })}
                            </section>
                        ) : (
                            <section className={styles.cardsFeminina}>
                                {!!resposta && Object?.values(resposta?.camisetas).map((item) => {
                                    return (
                                        <div className={styles.card}>
                                            <img src={item.img} />
                                            <p>{item.name}</p>
                                            <p>{item.price}</p>
                                            <p>{item.size}</p>
                                            <button onClick={() => window.open("https://web.whatsapp.com/send?phone=5511945988406")}>Comprar</button>
                                        </div>
                                    )
                                })}
                            </section>
                        )}
                        <h2>Calças</h2>
                        {filter?.length > 0 ? (
                            <section className={styles.cardsFeminina}>
                                {filtro.map((item) => {
                                    return (
                                        <div className={styles.card}>
                                            <img src={item.img} />
                                            <p>{item.name}</p>
                                            <p>{item.price}</p>
                                            <p>{item.size}</p>
                                            <button onClick={() => window.open("https://web.whatsapp.com/send?phone=5511945988406")}>Comprar</button>
                                        </div>
                                    )
                                })}
                            </section>
                        ) : (
                            <section className={styles.cardsFeminina}>
                                {resposta && Object?.values(resposta?.calcas).map((item) => {
                                    return (
                                        <div className={styles.card}>
                                            <img src={item.img} />
                                            <p>{item.name}</p>
                                            <p>{item.price}</p>
                                            <p>{item.size}</p>
                                            <button onClick={() => window.open("https://web.whatsapp.com/send?phone=5511945988406")}>Comprar</button>
                                        </div>
                                    )
                                })}
                            </section>
                        )}

                        <h2>Bermudas</h2>
                        {filter?.length > 0 ? (
                            <section className={styles.cardsFeminina}>
                                {filtrar.map((item) => {
                                    return (
                                        <div className={styles.card}>
                                            <img src={item.img} />
                                            <p>{item.name}</p>
                                            <p>{item.price}</p>
                                            <p>{item.size}</p>
                                            <button onClick={() => window.open("https://web.whatsapp.com/send?phone=5511945988406")}>Comprar</button>
                                        </div>
                                    )
                                })}
                            </section>

                        ) : (
                            <section className={styles.cardsFeminina}>
                                {resposta && Object?.values(resposta?.bermudas).map((item) => {
                                    return (
                                        <div className={styles.card}>
                                            <img src={item.img} />
                                            <p>{item.name}</p>
                                            <p>{item.price}</p>
                                            <p>{item.size}</p>
                                            <button onClick={() => window.open("https://web.whatsapp.com/send?phone=5511945988406")}>Comprar</button>
                                        </div>
                                    )
                                })}
                            </section>
                        )}
                    </div>
                </section>
            </div>
        </>
    )
}

