import Head from 'next/head'
import Image from 'next/image'
import styles from './styles.module.css'
import react, { useState, useEffect } from 'react'
import axios from 'axios'

export default function setorMasculino() {
    console.log('ok')
    const [grande, setGrande] = useState()
    const [medio, setMedio] = useState('')
    const [pequeno, setPequeno] = useState('')

    const [resposta, setResposta] = useState();
    const [selecionado, setSelecionado] = useState([]);

    useEffect(() => {
        axios.get('https://api-de-roupas-default-rtdb.firebaseio.com/roupas/masculina.json')
            .then(function (response) {
                setResposta(response?.data);
            })
    }, []);

    const [url, setUrl] = useState();
    useEffect(() => {
        if (typeof window !== "undefined") {
            const params = new URLSearchParams(window.location.search);
            let urlParams = undefined;
            params.forEach((value, key) => {
                urlParams = Object.assign({}, urlParams, {
                    [key]: value.toString(),
                });
            });
            console.log(urlParams, 'params')
            setUrl(urlParams);
        }
    }, []);

    console.log(url, 'url');

    // const teste = () => {            
    // setMedio(url=== medio)


    return (
        <>
            <div className='lojas'>
                <Head>
                    <title>Moda masculina</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <section className={styles.cabecalho}>
                    <h1>Moda masculina</h1>

                    <div className={styles.checkbox}>
                        {/* <label>Filtro</label> */}
                        <div onClick={() => teste}>
                            <input type={"checkbox"} value={grande} /><label>Grande</label>
                        </div>

{
                         const tamanho = url.filter(resposta, 'Medio') => {setMedio(e.target.value)}
                            return(
                         setMedio(url.size === medio)


                            )}


                        {tamanho.map((url.size, medio) => {
                             return (
                        <div onClick={() => window.location.href = `/setorMasculino?size=medio`}>
                            <input type={"checkbox"} onChange={(e) => setMedio(e.target.value)} /><label>Médio</label>
                        </div>
                             )})}

                        <div onClick={() => window.location.href = `/resultado?roupas=pequeno`}>
                            <input type={"checkbox"} onChange={(e) => setPequeno(e.target.value)} /><label>Pequeno</label>
                        </div>
                    </div>


                    <h2>Camisetas</h2>

                    <section className={styles.cardsMasculina}>
                        {resposta && Object?.values(resposta?.camisetas).map((item) => {
                            return (
                                <div className={styles.card}>
                                    <img src={item.img} />
                                    <p>{item.name}</p>
                                    <p>{item.price}</p>
                                    <p>{item.size}</p>
                                    <button onClick={() => window.open("https://web.whatsapp.com/send?phone=5511945988406")}>Comprar</button>
                                </div>
                            )
                        })}
                    </section>
                    <h2>Calças</h2>
                    <section className={styles.cardsMasculina}>
                        {resposta && Object?.values(resposta?.calcas).map((item) => {
                            return (
                                <div className={styles.card}>

                                    {/* onClick={() => click(item)}
                                    onChange={(e) => setSelecionado(e.target.value)}> */}
                                    <img src={item.img} />
                                    <p>{item.name}</p>
                                    <p>{item.price}</p>
                                    <p>{item.size}</p>
                                    <button onClick={() => window.open("https://web.whatsapp.com/send?phone=5511982620594")}>Comprar</button>
                                </div>
                            )
                        })}
                    </section>
                    <h2>Bermudas</h2>
                    <section className={styles.cardsMasculina}>
                        {resposta && Object?.values(resposta?.bermudas).map((item) => {
                            // console.log(item, 'kgfhkrtmhk');
                            return (
                                <div className={styles.card}
                                    onClick={() =>
                                        click(item)}
                                    onChange={(e) => setSelecionado(e.target.value)}>
                                    <img src={item.img} />
                                    <p>{item.name}</p>
                                    <p>{item.price}</p>
                                    <p>{item.size}</p>
                                    <button onClick={() => window.open("https://web.whatsapp.com/send?phone=55 11930234589")}>Comprar</button>
                                </div>
                            )
                        })}
                    </section>
                </section>
            </div>
        </>
    )


}        