import Head from 'next/head'
import Image from 'next/image'
import styles from './styles.module.css'
import react, { useState, useEffect } from 'react'
import axios from 'axios'

export default function setorMasculino() {


    const [resposta, setResposta] = useState();
    const [selecionado, setSelecionado] = useState([]);

    useEffect(() => {
        axios.get('https://api-de-roupas-default-rtdb.firebaseio.com/roupas/masculina.json')

            .then(function (response) {
                setResposta(response?.data);
            })
    }, []);
    const click = (produto) => {
        setSelecionado([...selecionado, produto])
        localStorage.setItem('selecionado', JSON.stringify(selecionado))
    }
    return (
        <>
            <Head>
                <title>Moda masculina</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className={styles.cabecalho}>
                {/* <input onchange={(e) => { setCamisa(e.target.value) }} /> */}
                {/* <main className={styles.main}> */}
                    <h1>Moda masculina</h1>
                {/* </main> */}

                {/* <div className={styles.roupas}>
                    <div className='checkbox'>
                    <input type={"checkbox"} /><label>grande</label>
                    <input type={"checkbox"} /><label>médio</label>
                    <input type={"checkbox"} /><label>pequeno</label>
                    </div>
                </div> */}
                    <h2>Camisetas</h2>
                <section className={styles.cardsMasculina}>
                    {resposta && Object?.values(resposta?.camisetas).map((item) => {
                        return (
                            <div className={styles.card}
                                onClick={() => click(item)}
                                onChange={(e) => setSelecionado(e.target.value)}>
                                <img src={item.img} />
                                <p>{item.name}</p>
                                <p>{item.price}</p>
                                <p>{item.size}</p>
                            </div>
                        )
                    })}
                </section>
                    <h2>Calças</h2>
                <section className={styles.cardsMasculina}>
                    {resposta && Object?.values(resposta?.calcas).map((item) => {
                        return (
                            <div className={styles.card
                            } onClick={() => click(item)}
                                onChange={(e) => setSelecionado(e.target.value)}>
                                <img src={item.img} />
                                <p>{item.name}</p>
                                <p>{item.price}</p>
                                <p>{item.size}</p>
                            </div>
                        )
                    })}
                </section>
                    <h2>Bermudas</h2>
                <section className={styles.cardsMasculina}>
                    {resposta && Object?.values(resposta?.bermudas).map((item) => {
                        return (
                            <div className={styles.card}
                                onClick={() =>
                                    click(item)}
                                onChange={(e) => setSelecionado(e.target.value)}>
                                <img src={item.img} />
                                <p>{item.name}</p>
                                <p>{item.price}</p>
                                <p>{item.size}</p>
                            </div>
                        )
                    })}
                </section>
            </section>
        </>
    )
}