import Head from 'next/head'
import Image from 'next/image'
import styles from './styles.module.css'
import react, { useState, useEffect } from 'react'
import axios from 'axios'

export default function Compras
() {

    const [resposta, setResposta] = useState([]);
    const [teste, setTeste] = useState([])

   
    const click = () => {
        // window.location.href = "/cadastro"
        localStorage.clear(resposta)
    }
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <button onClick={()=> click()}>voltar</button>

        </>
    )

}