import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Footer from '../components/Footer'
import Header from '../components/Header'
import SectionBanners from '../components/SectionBanners/Banner'
import SectionsCards from '../components/Sections/Cards'

export default function Home() {

    return (
        <section>
            <Head>
                <title>Na Moda</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                <Header />
            </header>
            <SectionBanners />
            <SectionsCards />
            <Footer />
        </section>

    )

}

