import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import QueryString from '../components/QueryString'

export default function Home() {

    return (
        <>
            <Head>
                <title>Na Moda</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>    
            <Banner />
            <QueryString />
            
        </>

    )

}

